# Generated by Django 6.1.dev20260226142936 on 2026-03-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=200)),
                ('descripcio', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('LL', 'Llibre'), ('VI', 'Vídeo'), ('CU', 'Curs')], default='LL', max_length=2)),
                ('data_publicacio', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
