# Generated by Django 6.1.dev20260226142936 on 2026-03-05 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurs',
            options={'verbose_name': 'Recurs', 'verbose_name_plural': 'Recursos'},
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('recurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.recurs')),
            ],
        ),
    ]
