# Generated by Django 6.0.3 on 2026-03-10 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_recurs_options_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='recurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='resources.recurs'),
        ),
    ]
