# Generated by Django 6.0.3 on 2026-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_tag_recurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurs',
            name='titol',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('recurs', 'nom')},
        ),
    ]
