# Generated by Django 6.0.3 on 2026-03-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_recurs_titol_alter_tag_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognoms', models.CharField(blank=True, max_length=150)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('nacionalitat', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('web', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='recurs',
            name='autors',
            field=models.ManyToManyField(blank=True, related_name='recursos', to='resources.autor'),
        ),
    ]
