# Generated by Django 6.0.3 on 2026-03-24 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_autor_recurs_autors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='data_naixement',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='web',
        ),
        migrations.RemoveField(
            model_name='recurs',
            name='autors',
        ),
        migrations.AddField(
            model_name='recurs',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='resources.autor'),
        ),
    ]
