# Generated by Django 6.0.3 on 2026-04-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_remove_autor_data_naixement_remove_autor_web_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurs',
            name='data_publicacio',
            field=models.DateField(),
        ),
    ]
