# Generated by Django 6.0.3 on 2026-04-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_alter_recurs_data_publicacio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurs',
            name='data_publicacio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
